### PR TITLE
Only register event listeners once

### PR DESCRIPTION
**Pull request by wesj**
Potential fix for issue 33.

### CODE REVIEW

**Comment by rwaldron** [comment]
Please don't edit "dist" files and adhere to the style of the existing code base

**Comment by wesj** [comment]
Heh. Boucoup is so nice in person. What an absolutely awful response to volunteer help.

I assume you mean add brackets on the single line if? I'll update the pull request tomorrow.

**Comment by rwaldron** [comment]
I'm not Bocoup, and if I were I'd say the same thing in a code review for any of my peers. It's clear that you didn't bother reading the contribution guidelines in the readme—otherwise this wouldn't hve been an issue. Do us both a favor and try to be less sensitive and assume first that I'm not attacking you personally, but I am trying to maintain a code base. Additionally, I cannot accept this until you agree to the CLA, after that, you need to make the change to the actual source file, not the built file.

Lastly, I'm very much interested in how you're attempting to fix this, so let's not get emotional and instead stick to writing code. Thanks.

**Comment by rwaldron** [comment]
Closing per notes in #33

**Pull request closed without merging**
